model:
  clip_dim: 512
  dropout_rate:
  - 0.1
  hidden_dim:
  - 256
  name: MobileCLIP-S1
  num_hidden_layers:
  - 1
  pretrained: datacompdr
optimizer:
  beta1:
  - 0.9
  beta2:
  - 0.999
  clip_lr:
  - 1.0e-05
  predictor_lr:
  - 5.0e-05
  weight_decay:
  - 0.001
paths:
  cache_dir: /kaggle/working/
  checkpoint_dir: ckpts
  data_dir: classification_dataset
  log_dir: logs
scheduler:
  gamma: 0.1
  milestones:
  - 4
  - 6
  - 10
training:
  accumulation_steps: 2
  batch_size: 4
  num_epochs: 1
wandb:
  api_key: your_wandb_api_key
  project: project_name
  run_name_template: '{hidden_dim}x{num_hidden_layers}_training'
  using: false
